### ISSUE TITLE
Cannot add word to personal dictionary

### ISSUE THREAD

**Issue by aricooperdavis** [openboard-team/openboard#620]
**Describe the bug**
I am unable to add words to my personal dictionary. When I press the "+ Add" button the screen goes briefly black then I'm brought back to the personal dictionary language selection screen.

**To Reproduce**
1. Go to 'Text correction' -> 'Personal dictionary' -> 'English (United Kingdom)'
2. Click on '+ Add'
3. The screen goes black and you are returned to the language selection screen

**Expected behavior**
I should be able to add a word to my personal dictionary.

**Screenshots**
![Screenshot_2022-06-07-17-42-49-287_com.android.settings.jpg](https://user-images.githubusercontent.com/8947634/172437209-a8f863f6-7496-4f18-94e3-fca5c4b84f7a.jpg)![Screenshot_2022-06-07-17-42-55-199_com.android.settings.jpg](https://user-images.githubusercontent.com/8947634/172437238-934eb03f-27b9-4a75-9d88-b0445b719c83.jpg)![Screenshot_2022-06-07-17-43-00-174_com.android.settings.jpg](https://user-images.githubusercontent.com/8947634/172437250-477a59b4-e4f2-4695-b52e-e7b5dfc998fb.jpg)

**Smartphone (please complete the following information):**
 - Device: POCO M4 Pro (fleur)
 - OS: Android 11, MIUI 13.0.6

**Additional context**
I am happy to test builds or provide crash logs if I can get some instructions on where to find them 🙂

**Comment by aricooperdavis** [comment]
Managed to grab a stack trace:

```
FATAL EXCEPTION: main
Process: com.android.settings, PID: 24150
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setSubtitle(java.lang.CharSequence)' on a null object reference
	at com.android.settings.inputmethod.UserDictionaryAddWordFragment.onCreateView(UserDictionaryAddWordFragment.java:91)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2897)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:527)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1324)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1477)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1555)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1608)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3046)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2990)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:458)
	at com.android.settingslib.core.lifecycle.ObservableActivity.onStart(ObservableActivity.java:74)
	at com.android.settings.SettingsActivity.onStart(SettingsActivity.java:522)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1434)
	at android.app.Activity.performStart(Activity.java:8173)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3624)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2202)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8096)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

**Comment by aricooperdavis** [comment]
For anyone experiencing the same issue, one workaround is to use a different app to manage your personal dictionary (they're all modifying the same internal Android personal dictionary). 

[User Dictionary Manager (UDM)](https://play.google.com/store/apps/details?id=com.usr.dict.mgr) worked for me.
