### ISSUE TITLE
App crashes on clipboard clear button.

### ISSUE THREAD

**Issue by Anonymous2716** [openboard-team/openboard#685]
**Describe the bug**
It didn't happen before. Noticed it few hours ago that if I click on clear clipboard button  I get system pop-up message `openboard stopped working....app info ....close app` openboard crashes. 
**To Reproduce**
1. Copy something or multiple string .
2. Click on 'clipboard clear button'
3. See error .app crashed.

**Screenshots**
I described it . 

**Smartphone (please complete the following information):**
 - OS: Android 9 , arm64 mediatek.

**Comment by MajeurAndroid** [comment]
Can you describe a bit more how this happened ? What did you copied ? With a gif or video for example. 
Thanks!

**Comment by Anonymous2716** [comment]
@MajeurAndroid I will try screen recording. I didnt clear app data yet.  Anything I copy one time or multiple time . and if i press the clear clipboard button app crashes. Give me an hour I will upload record.

**Comment by Anonymous2716** [comment]
@MajeurAndroid  here you go.

https://user-images.githubusercontent.com/78570872/185791602-12baaec9-3601-4d7b-8274-57ecddf5cb8b.mp4

**Comment by Anonymous2716** [comment]
@MajeurAndroid after a reboot it seems to be fixed . should I close this issue?

**Comment by MajeurAndroid** [comment]
@Anonymous2716 no ! At least not for now, we'll investigate this first.

**Comment by Anonymous2716** [comment]
@MajeurAndroid okay thanks.

**Comment by Anonymous2716** [comment]
@MajeurAndroid hi. It happened again . I copied some emoji gylphes and when I went to clear it the app crashed and this time rebooting or app clear cache/force stop didn't work.

**Comment by Anonymous2716** [comment]
```
11-17 16:17:02.564   855  1106 I PowerWrap: PowerHal_TouchBoost                                                                               11-17 16:17:02.581   389   389 I SurfaceFlinger: [Built-in Screen (type:0)] fps:25.746740,dur:1009.84,max:441.50,min:13.99                    11-17 16:17:02.586   389  1087 I BufferQueueProducer: [InputMethod#0](this:0x70cd09f800,id:6769,api:1,p:10127,c:389) queueBuffer: fps=0.04 dur=52655.70 max=52579.35 min=76.35                                                                                                              11-17 16:17:02.586   389   410 I BufferQueueProducer: [StatusBar#0](this:0x70cd0c9800,id:4,api:1,p:1318,c:389) queueBuffer: fps=0.98 dur=1024.37 max=1024.37 min=1024.37                                                                                                                    11-17 16:17:02.596   855  1106 I InputReader: AP_PROF:AppLaunch_dispatchPtr:Up                                                                11-17 16:17:02.596   855  1106 I PowerWrap: PowerHal_TouchBoost                                                                               11-17 16:17:02.599   855  3999 E clipboard: Exception:                                                                                        11-17 16:17:02.599   855  3999 E clipboard: java.lang.NullPointerException: Attempt to read from field 'android.content.ClipDescription android.content.ClipData.mClipDescription' on a null object reference                                                                               11-17 16:17:02.599   855  3999 E clipboard:     at android.content.ClipData.<init>(ClipData.java:749)                                         11-17 16:17:02.599   855  3999 E clipboard:     at com.android.server.clipboard.ClipboardService.setPrimaryClipInternal(ClipboardService.java:419)                                                                                                                                          11-17 16:17:02.599   855  3999 E clipboard:     at com.android.server.clipboard.ClipboardService$ClipboardImpl.clearPrimaryClip(ClipboardService.java:271)                                                                                                                                  11-17 16:17:02.599   855  3999 E clipboard:     at android.content.IClipboard$Stub.onTransact(IClipboard.java:72)                             11-17 16:17:02.599   855  3999 E clipboard:     at com.android.server.clipboard.ClipboardService$ClipboardImpl.onTransact(ClipboardService.java:237)                                                                                                                                        11-17 16:17:02.599   855  3999 E clipboard:     at android.os.Binder.execTransact(Binder.java:731)                                            11-17 16:17:02.601 10127 10127 D AndroidRuntime: Shutting down VM                                                                             11-17 16:17:02.602 10127 10127 E AndroidRuntime: FATAL EXCEPTION: main                                                                        11-17 16:17:02.602 10127 10127 E AndroidRuntime: Process: org.dslul.openboard.inputmethod.latin, PID: 10127                                   11-17 16:17:02.602 10127 10127 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.content.ClipDescription android.content.ClipData.mClipDescription' on a null object reference                                                                          11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:1956)                                11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1918)                                  11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1868)                                  11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.content.IClipboard$Stub$Proxy.clearPrimaryClip(IClipboard.java:199)        11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.content.ClipboardManager.clearPrimaryClip(ClipboardManager.java:117)       11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at org.dslul.openboard.inputmethod.compat.ClipboardManagerCompat.clearPrimaryClip(ClipboardManagerCompat.java:13)                                                                                                                   11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at org.dslul.openboard.inputmethod.latin.ClipboardHistoryManager.clearHistory(ClipboardHistoryManager.kt:87)                                                                                                                        11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at org.dslul.openboard.inputmethod.keyboard.clipboard.ClipboardHistoryView.onClick(ClipboardHistoryView.kt:194)                                                                                                                     11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.view.View.performClick(View.java:6603)                                     11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:6576)                             11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.view.View.access$3100(View.java:780)                                       11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:26090)                                11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)                                11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)                                11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)                                            11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6702)                          11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)                                     11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)  11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)                       11-17 16:17:02.602 10127 10127 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:                                   11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.content.ClipData.<init>(ClipData.java:749)                                 11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at com.android.server.clipboard.ClipboardService.setPrimaryClipInternal(ClipboardService.java:419)                                                                                                                                  11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at com.android.server.clipboard.ClipboardService$ClipboardImpl.clearPrimaryClip(ClipboardService.java:271)                                                                                                                          11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.content.IClipboard$Stub.onTransact(IClipboard.java:72)                     11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at com.android.server.clipboard.ClipboardService$ClipboardImpl.onTransact(ClipboardService.java:237)                                                                                                                                11-17 16:17:02.602 10127 10127 E AndroidRuntime:                                                                                              11-17 16:17:02.606   855   935 I ActivityManager: Showing crash dialog for package org.dslul.openboard.inputmethod.latin u0                   11-17 16:17:02.632   855   935 D ViewRootImpl[latin]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false                                                                                      11-17 16:17:02.637   855   935 V WindowManager: Changing focus from Window{f469952 u0 com.termux/com.termux.app.TermuxActivity} to Window{3aa3290 u0 Application Error: org.dslul.openboard.inputmethod.latin} Callers=com.android.server.wm.WindowManagerService.addWindow:1519 com.android.server.wm.Session.addToDisplay:205 android.view.ViewRootImpl.setView:771 android.view.WindowManagerGlobal.addView:356
11-17 16:17:02.637   855   935 D WindowManager: Input focus has changed to Window{3aa3290 u0 Application Error: org.dslul.openboard.inputmethod.latin}                                                                                                                                      11-17 16:17:02.639   855   946 I WindowManager: Focus moving from Window{f469952 u0 com.termux/com.termux.app.TermuxActivity} to Window{3aa3290 u0 Application Error: org.dslul.openboard.inputmethod.latin}                                                                                11-17 16:17:02.650   389   411 I BufferQueue: [unnamed-389-6770](this:0x70c9147000,id:6770,api:0,p:-1,c:-1) BufferQueue core=(389:/system/bin/surfaceflinger)                                                                                                                               11-17 16:17:02.651   389   411 I BufferQueueConsumer: [unnamed-389-6770](this:0x70c9147000,id:6770,api:0,p:-1,c:389) connect(C): consumer=(389:/system/bin/surfaceflinger) controlledByApp=false                                                                                            11-17 16:17:02.651   389   411 I BufferQueueConsumer: [unnamed-389-6770](this:0x70c9147000,id:6770,api:0,p:-1,c:389) setConsumerName: unnamed-389-6770                                                                                                                                      11-17 16:17:02.651   389   411 I BufferQueueConsumer: [Application Error: org.dslul.openboard.inputmethod.latin#0](this:0x70c9147000,id:6770,api:0,p:-1,c:389) setConsumerName: Application Error: org.dslul.openboard.inputmethod.latin#0                                                  11-17 16:17:02.651   389   411 I BufferQueueConsumer: [Application Error: org.dslul.openboard.inputmethod.latin#0](this:0x70c9147000,id:6770,api:0,p:-1,c:389) setDefaultBufferSize: width=774 height=372                                                                                   11-17 16:17:02.653   855   935 D Surface : Surface::allocateBuffers(this=0x7974b5a000)                                                        11-17 16:17:02.653   855  4039 D Surface : Surface::connect(this=0x7974b5a000,api=1)                                                          11-17 16:17:02.654   389  1087 I BufferQueueProducer: [Application Error: org.dslul.openboard.inputmethod.latin#0](this:0x70c9147000,id:6770,api:1,p:855,c:389) connect(P): api=1 producer=(855:system_server) producerControlledByApp=false                                                11-17 16:17:02.661   855  4039 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000                                                                                                              11-17 16:17:02.711   855   946 I WindowManager: Losing delayed focus: Window{f469952 u0 com.termux/com.termux.app.TermuxActivity}
```

**Comment by Anonymous2716** [comment]
````
11-17 16:17:02.564   855  1106 I PowerWrap: PowerHal_TouchBoost                                                                               

11-17 16:17:02.581   389   389 I SurfaceFlinger: [Built-in Screen (type:0)] fps:25.746740,dur:1009.84,max:441.50,min:13.99                    
11-17 16:17:02.586   389  1087 I BufferQueueProducer: [InputMethod#0](this:0x70cd09f800,id:6769,api:1,p:10127,c:389) queueBuffer: fps=0.04 dur=52655.70 max=52579.35 min=76.35                                                                                                              
11-17 16:17:02.586   389   410 I BufferQueueProducer: [StatusBar#0](this:0x70cd0c9800,id:4,api:1,p:1318,c:389) queueBuffer: fps=0.98 dur=1024.37 max=1024.37 min=1024.37                                                                                                                    
11-17 16:17:02.596   855  1106 I InputReader: AP_PROF:AppLaunch_dispatchPtr:Up                                                                
11-17 16:17:02.596   855  1106 I PowerWrap: PowerHal_TouchBoost                                                                               
11-17 16:17:02.599   855  3999 E clipboard: Exception:                                                                                        
11-17 16:17:02.599   855  3999 E clipboard: java.lang.NullPointerException: Attempt to read from field 'android.content.ClipDescription android.content.ClipData.mClipDescription' on a null object reference                                                                               
11-17 16:17:02.599   855  3999 E clipboard:     at android.content.ClipData.<init>(ClipData.java:749)                                         
11-17 16:17:02.599   855  3999 E clipboard:     at com.android.server.clipboard.ClipboardService.setPrimaryClipInternal(ClipboardService.java:419)                                                                                                                                          
11-17 16:17:02.599   855  3999 E clipboard:     at com.android.server.clipboard.ClipboardService$ClipboardImpl.clearPrimaryClip(ClipboardService.java:271)                                                                                                                                  
11-17 16:17:02.599   855  3999 E clipboard:     at android.content.IClipboard$Stub.onTransact(IClipboard.java:72)                             
11-17 16:17:02.599   855  3999 E clipboard:     at com.android.server.clipboard.ClipboardService$ClipboardImpl.onTransact(ClipboardService.java:237)                                                                                                                                        
11-17 16:17:02.599   855  3999 E clipboard:     at android.os.Binder.execTransact(Binder.java:731)                                            
11-17 16:17:02.601 10127 10127 D AndroidRuntime: Shutting down VM                                                                             
11-17 16:17:02.602 10127 10127 E AndroidRuntime: FATAL EXCEPTION: main                                                                        
11-17 16:17:02.602 10127 10127 E AndroidRuntime: Process: org.dslul.openboard.inputmethod.latin, PID: 10127                                   
11-17 16:17:02.602 10127 10127 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.content.ClipDescription android.content.ClipData.mClipDescription' on a null object reference                                                                          
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:1956)                                
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1918)                                  
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1868)                                  
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.content.IClipboard$Stub$Proxy.clearPrimaryClip(IClipboard.java:199)        
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.content.ClipboardManager.clearPrimaryClip(ClipboardManager.java:117)       
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at org.dslul.openboard.inputmethod.compat.ClipboardManagerCompat.clearPrimaryClip(ClipboardManagerCompat.java:13)                                                                                                                   
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at org.dslul.openboard.inputmethod.latin.ClipboardHistoryManager.clearHistory(ClipboardHistoryManager.kt:87)                                                                                                                        
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at org.dslul.openboard.inputmethod.keyboard.clipboard.ClipboardHistoryView.onClick(ClipboardHistoryView.kt:194)                                                                                                                     
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.view.View.performClick(View.java:6603)                                     
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:6576)                             
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.view.View.access$3100(View.java:780)                                       
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:26090)                                
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)                                
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)                                
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)                                            
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6702)                          
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)                                     
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)  
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)                       
11-17 16:17:02.602 10127 10127 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:                                   
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.content.ClipData.<init>(ClipData.java:749)                                 
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at com.android.server.clipboard.ClipboardService.setPrimaryClipInternal(ClipboardService.java:419)                                                                                                                                  
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at com.android.server.clipboard.ClipboardService$ClipboardImpl.clearPrimaryClip(ClipboardService.java:271)                                                                                                                          
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at android.content.IClipboard$Stub.onTransact(IClipboard.java:72)                     
11-17 16:17:02.602 10127 10127 E AndroidRuntime:        at com.android.server.clipboard.ClipboardService$ClipboardImpl.onTransact(ClipboardService.java:237)                                                                                                                                
11-17 16:17:02.602 10127 10127 E AndroidRuntime:                                                                                              
11-17 16:17:02.606   855   935 I ActivityManager: Showing crash dialog for package org.dslul.openboard.inputmethod.latin u0                   
11-17 16:17:02.632   855   935 D ViewRootImpl[latin]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false                                                                                      
11-17 16:17:02.637   855   935 V WindowManager: Changing focus from Window{f469952 u0 com.termux/com.termux.app.TermuxActivity} to Window{3aa3290 u0 Application Error: org.dslul.openboard.inputmethod.latin} Callers=com.android.server.wm.WindowManagerService.addWindow:1519 com.android.server.wm.Session.addToDisplay:205 android.view.ViewRootImpl.setView:771 android.view.WindowManagerGlobal.addView:356

11-17 16:17:02.637   855   935 D WindowManager: Input focus has changed to Window{3aa3290 u0 Application Error: org.dslul.openboard.inputmethod.latin}                                                                                                                                      
11-17 16:17:02.639   855   946 I WindowManager: Focus moving from Window{f469952 u0 com.termux/com.termux.app.TermuxActivity} to Window{3aa3290 u0 Application Error: org.dslul.openboard.inputmethod.latin}                                                                                
11-17 16:17:02.650   389   411 I BufferQueue: [unnamed-389-6770](this:0x70c9147000,id:6770,api:0,p:-1,c:-1) BufferQueue core=(389:/system/bin/surfaceflinger)                                                                                                                               

11-17 16:17:02.651   389   411 I BufferQueueConsumer: [unnamed-389-6770](this:0x70c9147000,id:6770,api:0,p:-1,c:389) connect(C): consumer=(389:/system/bin/surfaceflinger) controlledByApp=false                                                                                            

11-17 16:17:02.651   389   411 I BufferQueueConsumer: [unnamed-389-6770](this:0x70c9147000,id:6770,api:0,p:-1,c:389) setConsumerName: unnamed-389-6770                                                                                                                                      

11-17 16:17:02.651   389   411 I BufferQueueConsumer: [Application Error: org.dslul.openboard.inputmethod.latin#0](this:0x70c9147000,id:6770,api:0,p:-1,c:389) setConsumerName: Application Error: org.dslul.openboard.inputmethod.latin#0                                                  

11-17 16:17:02.651   389   411 I BufferQueueConsumer: [Application Error: org.dslul.openboard.inputmethod.latin#0](this:0x70c9147000,id:6770,api:0,p:-1,c:389) setDefaultBufferSize: width=774 height=372                                                                                   

11-17 16:17:02.653   855   935 D Surface : Surface::allocateBuffers(this=0x7974b5a000)                                                        

11-17 16:17:02.653   855  4039 D Surface : Surface::connect(this=0x7974b5a000,api=1)                                                          

11-17 16:17:02.654   389  1087 I BufferQueueProducer: [Application Error: org.dslul.openboard.inputmethod.latin#0](this:0x70c9147000,id:6770,api:1,p:855,c:389) connect(P): api=1 producer=(855:system_server) producerControlledByApp=false                                                

11-17 16:17:02.661   855  4039 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000                                                                                                              

11-17 16:17:02.711   855   946 I WindowManager: Losing delayed focus: Window{f469952 u0 com.termux/com.termux.app.TermuxActivity}
```

**Comment by Anonymous2716** [comment]
Just for reference. https://stackoverflow.com/a/39504849/20842140
